cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  image: ${docker_registry}redhawk/maven:3-jdk-8
  stage: build
  script:
    - mvn install sonar:sonar -P sign -P develop-2.1 -P with-metadata
  artifacts:
    paths:
      - tests/*/target/surefire-reports/*.xml
    expire_in: 1 day
  #Skip on tag of following format
  except:
    - /^(\d+\.)?(\d+)?(\.\d+)$/

jenkins:
  image: centos:7
  stage: deploy
  dependencies: []
  before_script:
    - echo "Deploying to $jenkins_url/job/$CI_PROJECT_NAMESPACE/job/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
  script:
    - if [ -n "$jenkins_url" ]; then
        curl --insecure -X POST $jenkins_url/job/$CI_PROJECT_NAMESPACE/job/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME/buildWithParameters?pipeline_id=$CI_PIPELINE_ID --user $jenkins_user:$jenkins_api_token;
      fi
  only:
    - branches

trigger-product:
  image: centos:7
  stage: deploy
  dependencies: []
  script:
    - curl --insecure -X POST -F ref=$CI_COMMIT_REF_NAME
                              -F token=$product_token
                              -F "variables[triggering_project]=$CI_PROJECT_NAME"
                              -F "variables[triggering_ref]=$CI_COMMIT_SHA"
                              -F "variables[triggering_ref_name]=$CI_COMMIT_REF_NAME"
                              $product_url
  only:
    - branches
